# Generated by Django 3.2.4 on 2021-07-13 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('upc', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nama_produk', models.CharField(max_length=100)),
                ('kandungan', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('manfaat', models.TextField(blank=True, max_length=300)),
                ('kelebihan', models.TextField(blank=True, max_length=300)),
                ('kekurangan', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
