# Generated by Django 3.2.4 on 2021-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='jenis_produk',
            field=models.CharField(choices=[('Make Up', 'Make Up'), ('Skincare', 'Skincare'), ('Bodycare', 'Bodycare'), ('Vitamin', 'Vitamin'), ('Obat', 'Obat')], default='Make Up', max_length=30),
        ),
    ]
