# Generated by Django 3.2.4 on 2021-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_produk_jenis_produk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='upc',
            new_name='nomor_barcode',
        ),
        migrations.AlterField(
            model_name='produk',
            name='kekurangan',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kelebihan',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='produk',
            name='manfaat',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
