# Generated by Django 3.2.4 on 2021-07-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alamat_domisili', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('no_rekening', models.CharField(max_length=20, unique=True)),
                ('pengalaman_praktek', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alamat_domisili', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kulit', models.CharField(choices=[('Kering', 'Kering'), ('Berminyak', 'Berminyak'), ('Normal', 'Normal'), ('Sensitif', 'Sensitif')], default='Kering', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
