# Generated by Django 3.2.4 on 2021-07-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='username',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='username',
            new_name='id',
        ),
    ]
