# Generated by Django 3.2.4 on 2021-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210715_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='ktp',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='pengalaman_praktek',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
