# Generated by Django 3.2.4 on 2021-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210715_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='izin_praktek',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='pengalaman_praktek',
            field=models.IntegerField(default=0),
        ),
    ]
