# Generated by Django 3.2.4 on 2021-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20210715_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='izin_praktek',
            field=models.ImageField(blank=True, upload_to='images/izin/'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='ktp',
            field=models.ImageField(blank=True, upload_to='images/ktp/'),
        ),
    ]
